//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteoApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeteoApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AddLocation_Cancel {
            get {
                return ResourceManager.GetString("AddLocation_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City not found or does not exist. Please try again..
        /// </summary>
        internal static string AddLocation_ErrorCityNotFound {
            get {
                return ResourceManager.GetString("AddLocation_ErrorCityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the map or type a city name..
        /// </summary>
        internal static string AddLocation_ErrorEmptyCity {
            get {
                return ResourceManager.GetString("AddLocation_ErrorEmptyCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string AddLocation_ErrorTitle {
            get {
                return ResourceManager.GetString("AddLocation_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AddLocation_OK {
            get {
                return ResourceManager.GetString("AddLocation_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the map or type a city name.
        /// </summary>
        internal static string AddLocation_Placeholder {
            get {
                return ResourceManager.GetString("AddLocation_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string AddLocation_Save {
            get {
                return ResourceManager.GetString("AddLocation_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location.
        /// </summary>
        internal static string AddLocation_Title {
            get {
                return ResourceManager.GetString("AddLocation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown location.
        /// </summary>
        internal static string AddLocation_UnknownPlace {
            get {
                return ResourceManager.GetString("AddLocation_UnknownPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string AppShell_HomeTab {
            get {
                return ResourceManager.GetString("AppShell_HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteo App.
        /// </summary>
        internal static string AppShell_Title {
            get {
                return ResourceManager.GetString("AppShell_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string MeteoItem_Max {
            get {
                return ResourceManager.GetString("MeteoItem_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string MeteoItem_Min {
            get {
                return ResourceManager.GetString("MeteoItem_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string MeteoItem_Title {
            get {
                return ResourceManager.GetString("MeteoItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View weather trend.
        /// </summary>
        internal static string MeteoItem_ViewForecast {
            get {
                return ResourceManager.GetString("MeteoItem_ViewForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🌐 EN / IT.
        /// </summary>
        internal static string MeteoList_ChangeLanguage {
            get {
                return ResourceManager.GetString("MeteoList_ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Location.
        /// </summary>
        internal static string MeteoList_CurrentLocation {
            get {
                return ResourceManager.GetString("MeteoList_CurrentLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MeteoList_Delete {
            get {
                return ResourceManager.GetString("MeteoList_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Cities.
        /// </summary>
        internal static string MeteoList_SavedCities {
            get {
                return ResourceManager.GetString("MeteoList_SavedCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Cities.
        /// </summary>
        internal static string MeteoList_Title {
            get {
                return ResourceManager.GetString("MeteoList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving weather data.
        /// </summary>
        internal static string Weather_Error {
            get {
                return ResourceManager.GetString("Weather_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Weather_Loading {
            get {
                return ResourceManager.GetString("Weather_Loading", resourceCulture);
            }
        }
    }
}
